### ISSUE TITLE
Cannot use email alias for user management

### ISSUE THREAD

**Issue by abhay-ramesh** [n8n-io/n8n-docs#1047]
#### In [docs/hosting/authentication/user-management-self-hosted.md](https://github.com/n8n-io/n8n-docs/blob/main/docs/hosting/authentication/user-management-self-hosted.md)
*Change:*
| `N8N_SMTP_SENDER` | string | You can select the sender name from the sender addresses. Example: "N8N _contact@n8n.com_"| Required |

*To:*
| `N8N_SMTP_SENDER` | string | You can select the sender name from the sender addresses. Example: "N8N _\<contact@n8n.com>_"| Required |

**And**

#### In [docs/hosting/environment-variables/environment-variables.md](https://github.com/n8n-io/n8n-docs/blob/main/docs/hosting/environment-variables/environment-variables.md)
*Change:*
| `N8N_SMTP_SENDER` | String | - |You can select the sender name from the sender addresses. Example: `N8N _contact@n8n.com_`| 

*To:*
| `N8N_SMTP_SENDER` | String | - | You can select the sender name from the sender addresses. Example: `N8N <contact@n8n.com>`|

**Comment by StarfallProjects** [comment]
Hi @abhay-ramesh could you say more about this? Which docs page has an issue? Or is this an issue with the product itself, rather than the docs?

**Comment by abhay-ramesh** [comment]
### Found the problem

#### In [docs/hosting/authentication/user-management-self-hosted.md](https://github.com/n8n-io/n8n-docs/blob/main/docs/hosting/authentication/user-management-self-hosted.md)
*Change:*
| `N8N_SMTP_SENDER` | string | You can select the sender name from the sender addresses. Example: "N8N _contact@n8n.com_"| Required |

*To:*
| `N8N_SMTP_SENDER` | string | You can select the sender name from the sender addresses. Example: "N8N _\<contact@n8n.com>_"| Required |

**And**

#### In [docs/hosting/environment-variables/environment-variables.md](https://github.com/n8n-io/n8n-docs/blob/main/docs/hosting/environment-variables/environment-variables.md)
*Change:*
| `N8N_SMTP_SENDER` | String | - |You can select the sender name from the sender addresses. Example: `N8N _contact@n8n.com_`| 

*To:*
| `N8N_SMTP_SENDER` | String | - | You can select the sender name from the sender addresses. Example: `N8N <contact@n8n.com>`|

**Comment by StarfallProjects** [comment]
Thanks for the report. Fix PR is: https://github.com/n8n-io/n8n-docs/pull/1048
