### ISSUE TITLE
Dead link in "We’ve been busy ✨" popup

### ISSUE THREAD

**Issue by PvUtrix** [n8n-io/n8n-docs#1359]
The link here
<img width="496" alt="image" src="https://user-images.githubusercontent.com/32957084/233125434-3e97ce3e-3663-46fb-b45c-c291dce8607d.png">
https://docs.n8n.io/getting-started/installation/updating.html
does not exist anymore

**Comment by StarfallProjects** [comment]
Hi @PvUtrix thanks for this. I've:

1. Added the updating info to the top of release notes: https://docs.n8n.io/release-notes/
2. Submitted a PR to update the link to go directly to release notes: https://github.com/n8n-io/n8n/pull/6018 (it already redirects there, but makes sense to clean up the link)

**Comment by PvUtrix** [comment]
Hi @StarfallProjects, 
It seems the links you mention in 1. lead to Installation and not updating - https://docs.n8n.io/hosting/installation/
I was unable to get to information on updating the self hosted version. I was able to do it myself, but the info is not there.

**Comment by StarfallProjects** [comment]
@PvUtrix the installation guides for npm and Docker include sections on how to update. I've added direct links to npm and docker from the updating snippet.
