### ISSUE TITLE
The "longer introduction" quickstart guide is out of date

### ISSUE THREAD

**Issue by bruc3mackenzi3** [n8n-io/n8n-docs#1391]
This is my first time using n8n.  Working through the ["slightly longer introduction"](https://docs.n8n.io/try-it-out/longer-introduction/) I observed the following inconsistencies:

## [Step four](https://docs.n8n.io/try-it-out/longer-introduction/#step-four-add-the-nasa-node-and-set-up-credentials)
Instructions 4 and 5 now occur in the opposite order.

Instead of _Select the Credential for NASA API dropdown._, this appears:

![image](https://user-images.githubusercontent.com/116661692/236623971-ef5ee9f7-9db2-4260-ae14-3ee8dc1e7e1f.png)

Only after selecting the resource does the credential UI appear:

![image](https://user-images.githubusercontent.com/116661692/236624029-006e0e80-d8a3-4303-95d7-202be71e430d.png)

## [Step five](https://docs.n8n.io/try-it-out/longer-introduction/#step-five-add-logic-with-the-if-node)

Instruction 5. b) does not match the UI:

_Select Current Node > Input Data > JSON > classType. n8n adds the expression to the Expression editor_

<img width="414" alt="image" src="https://user-images.githubusercontent.com/116661692/236623548-3765334c-bff9-41f0-bde7-7b874fd8cc1f.png">

To get the variable reference in the field, I dragged classType from the left side of the UI.

_Close the expressions editor to return to the node_

By default the expressions editor is not opened; the variable is edited inline.

## Conclusion

There are additional inconsistencies, but you get the idea.

Is this something the community is aware of, and if so is an update to the Quickstart prioritized?  If not I am willing to take this on.

**Comment by Joffcom** [comment]
Hey @bruc3mackenzi3,

Good spot, I will get this updated shortly.

**Comment by StarfallProjects** [comment]
Hi @bruc3mackenzi3 thanks for the report. I've reviewed both the quickstarts and fixed the issues you flagged, alongside a few other updates.

For future reference: if you see things you want to fix, feel free to directly submit a PR if you want to :-)

**Comment by bruc3mackenzi3** [comment]
Thanks for the update.  I will keep this in mind for the future :)
