### ISSUE TITLE
n8n-nodes-base.debughelper.md broken links

### ISSUE THREAD

**Issue by NikolaiKazintsevHORS** [n8n-io/n8n-docs#1506]
### 2 links follows to 404:
* https://github.com/n8n-io/n8n-docs/blob/443cbd4f95c80ecc9b5af889b6e01e9c6fd62108/docs/integrations/builtin/core-nodes/n8n-nodes-base.debughelper.md?plain=1#L12
* https://github.com/n8n-io/n8n-docs/blob/443cbd4f95c80ecc9b5af889b6e01e9c6fd62108/docs/integrations/builtin/core-nodes/n8n-nodes-base.debughelper.md?plain=1#L38

**Comment by StarfallProjects** [comment]
@NikolaiKazintsevHORS thanks! I've given our website team a heads-up, it look like that node isn't properly on the website yet. I'll keep this open and check back.

**Comment by StarfallProjects** [comment]
@NikolaiKazintsevHORS this should now be fixed. Thanks again for the report 🙏
