### ISSUE TITLE
Little merge typo in release notes

### ISSUE THREAD

**Issue by thochra** [n8n-io/n8n-docs#1511]
Hi there 👋 

I just noticed a little typo resulting of a merge conflict over there: https://github.com/n8n-io/n8n-docs/blob/0f73ee600e1f3d5e2ed4182f772fdfb9e3dc3614/docs/release-notes.md?plain=1#L1061

There are 3 areas where we can see the merge conflicts.

**Comment by StarfallProjects** [comment]
Fixed, thank you! (it may need a few minutes to build and re-deploy)
