### ISSUE TITLE
Trello API Authentication

### ISSUE THREAD

**Issue by lukeschantz** [n8n-io/n8n-docs#1867]
Hello n8n team,

I'm reaching out to bring to your attention an issue I've encountered with the Trello integration in n8n. It appears that Trello has recently updated how they manage API keys and authentication.

1. **Documentation Link Issue**: The current n8n documentation for Trello integration directs users to [https://trello.com/app-key](https://trello.com/app-key) for obtaining API keys. However, this link now redirects users to a new page ([https://trello.com/power-ups/admin/](https://trello.com/power-ups/admin/)) with a notice about changes in managing API keys.

2. **Change in Authentication Method**: On the new Trello page, it is mentioned that "Each Power-Up can now have a unique API key and be managed by any collaborators," and there's an emphasis on managing these keys from the "Power-Up Admin Portal." Most notably, what was previously referred to as an 'API Token' is now termed as an 'API Secret.'

3. **Integration Issue**: In the n8n Trello node configuration, it still asks for an 'API Key' and 'API Token.' When I try to use the new 'API Key' and 'API Secret' from Trello in these fields, I encounter a 401 authentication error.

I seems the n8n Trello node needs an update to align with these new changes from Trello. It would be greatly appreciated if you could look into this issue and update the integration process accordingly. This change is crucial for ensuring smooth and continued integration between n8n and Trello.  I tried this from both my local and your cloud.  I added my localhost, my IP address and the cloud address of the workspace to the Trello allowed origins.

Thank you for your attention to this matter.

Best regards,

Luke

**Comment by StarfallProjects** [comment]
Hi @lukeschantz thanks for reporting this. Have passed it on to the nodes team and will let you know what we do.

**Comment by Joffcom** [comment]
Hey @lukeschantz,

It looks like the old API keys still work but when using the power apps you will need to generate your token by cliking the link below, This can then be pasted into the credential and will get you up and running.

<img width="919" alt="image" src="https://github.com/n8n-io/n8n-docs/assets/4688521/bd668dc2-21e7-43fc-88cd-1afd2ff639e4">

Oddly for my account the `https://trello.com/app-key` url works as expected once I am signed in, It looks a good solution for this though would be to add support for the OAuth1 option which should get this working.

**Comment by lukeschantz** [comment]
Thanks so much for the quick reply.  Somehow I missed that Token link!
