### ISSUE TITLE
Dead Link At Docs -> Integrations -> Built-in nodes -> Core nodes -> Convert to File

### ISSUE THREAD

**Issue by jlwainwright** [n8n-io/n8n-docs#1868]
Image:
<img width="792" alt="image" src="https://github.com/n8n-io/n8n-docs/assets/17202115/92b818c5-db41-4008-adc6-f4637149285e">

Link:
[https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.extractfromfile/?utm_source=n8n_app&utm_medium=node_settings_modal-credential_link&utm_campaign=n8n-nodes-base.extractFromFile](url)

**Comment by StarfallProjects** [comment]
Hiya! Thanks for the report. Looks like we're missing a couple of nodes (including that one) on the website examples list. Will look into this.

**Comment by StarfallProjects** [comment]
@jlwainwright  This should now be fixed. Thank you again for the heads-up! 🎉
