### ISSUE TITLE
Shopify doc doesn't reflect the private app settings

### ISSUE THREAD

**Issue by srokatonie** [n8n-io/n8n-docs#1876]
https://docs.n8n.io/integrations/builtin/credentials/shopify/

Shopify private apps are not called private apps any more and keys have changed:

- Admin API access token
- API key
- API secret key

**Comment by StarfallProjects** [comment]
@srokatonie thanks for the report!

@Joffcom I'm updating the affected doc to follow our simplified template and link to Shopify docs. However, I wonder if we also need to look at auth in the node itself (or maybe just the field labels?) Assuming this is the API we use: https://shopify.dev/docs/api/admin-rest#authentication ?

**Comment by srokatonie** [comment]
@StarfallProjects No problem. The layout completely changed. See here: https://community.n8n.io/t/shopify-node-seetings/39543

**Comment by StarfallProjects** [comment]
Closing this now. I've simplified the doc to remove outdated info. And our nodes dev team has a ticket to update the node.

Thanks again for raising the issue 🙏
