### ISSUE TITLE
course level 2 exercise looping with wrong solution

### ISSUE THREAD

**Issue by galdianoo** [n8n-io/n8n-docs#1892]
url: https://docs.n8n.io/courses/level-two/chapter-3/#exercise_1

**Comment by bartv42** [comment]
Thanks for reporting this! Just to make sure, the way I read that report is that we should update the screenshot with something like this, to reflect the new loop node?

**Comment by galdianoo** [comment]
> @galdianoo Thanks for reporting this! Just to make sure, the way I read that report is that we should update the screenshot with something like this, to reflect the new loop node?

yes, actually, i just finished the level 2 and there are additional room for improvement, such as:

- lack of information of the need to add "My ID: {token}" in error workflow
> without that id, the node from discord only

**Comment by bartv42** [comment]
Hi @galdianoo, thanks for your input!

I just updated all screenshots for the L1+L2 courses, so perhaps some of your feedback is no longer valid - can you check?

> 1) lack of information within the steps to convert to pdf

I'm not entirely sure which part you're referring to here since we don't convert anything TO PDF, only FROM PDF. Can you point me to the right place?

> 2) lack of details within the configuration of nodes

The code in the solution does include the input of the 'date & time' node. Is that what you meant?

![image](https://github.com/n8n-io/n8n-docs/assets/6816469/1586578e-58ec-42ca-85fc-9af1bcab4a7e)

3) send message to discord channel 2

The Level 2 course requires different credentials, and you'll have to sign up again to get them. See on the first page:

https://docs.n8n.io/courses/level-two/#how-do-i-complete-the-course

> 4) lack of information of the need to add "My ID: {token}" in error workflow

You're right! I have pushed a fix to change this step to:

* Text: The workflow `{workflow name}` failed, with the error message: `{execution error message}`. Last node executed: `{name of the last executed node}`. Check this workflow execution here: `{execution URL}` My Unique ID: `{your ID from the course signup email}`

> 5) all in all, it lacks the solution for the exercises

I appreciate all the feedback you can give me! If you get stuck, other people will too.

**Comment by galdianoo** [comment]
> Hi @galdianoo, thanks for your input!
> 
> I just updated all screenshots for the L1+L2 courses, so perhaps some of your feedback is no longer valid - can you check?
> 
> > 1. lack of information within the steps to convert to pdf
> 
> I'm not entirely sure which part you're referring to here since we don't convert anything TO PDF, only FROM PDF. Can you point me to the right place?
> 
> > 2. lack of details within the configuration of nodes
> 
> The code in the solution does include the input of the 'date & time' node. Is that what you meant?
> 
> ![image](https://private-user-images.githubusercontent.com/6816469/312041792-1586578e-58ec-42ca-85fc-9af1bcab4a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzAzNTksIm5iZiI6MTcxMDM3MDA1OSwicGF0aCI6Ii82ODE2NDY5LzMxMjA0MTc5Mi0xNTg2NTc4ZS01OGVjLTQyY2EtODVmYy05YWYxYmNhYjRhN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMjI0NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc1NjUwYmIyOGUyMmM3N2M5MWM2MTA0ZWEwNzFlMjhkOTU1NDgwZDA3MmE1YzczYWE0M2U0OWYwN2MzYmEzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z37mVs_I_WjJ7cMLJGIzBPqxgbmzgVGGzNaVdcojNDM)
> 
> 3. send message to discord channel 2
> 
> The Level 2 course requires different credentials, and you'll have to sign up again to get them. See on the first page:
> 
> https://docs.n8n.io/courses/level-two/#how-do-i-complete-the-course
> 
> > 4. lack of information of the need to add "My ID: {token}" in error workflow
> 
> You're right! I have pushed a fix to change this step to:
> 
> * Text: The workflow `{workflow name}` failed, with the error message: `{execution error message}`. Last node executed: `{name of the last executed node}`. Check this workflow execution here: `{execution URL}` My Unique ID: `{your ID from the course signup email}`
> 
> > 5. all in all, it lacks the solution for the exercises
> 
> I appreciate all the feedback you can give me! If you get stuck, other people will too.



> Hi @galdianoo, thanks for your input!
> 
> I just updated all screenshots for the L1+L2 courses, so perhaps some of your feedback is no longer valid - can you check?
> 
> > 1. lack of information within the steps to convert to pdf
> 
> I'm not entirely sure which part you're referring to here since we don't convert anything TO PDF, only FROM PDF. Can you point me to the right place?
> 
> > 2. lack of details within the configuration of nodes
> 
> The code in the solution does include the input of the 'date & time' node. Is that what you meant?
> 
> ![image](https://private-user-images.githubusercontent.com/6816469/312041792-1586578e-58ec-42ca-85fc-9af1bcab4a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzAzNTksIm5iZiI6MTcxMDM3MDA1OSwicGF0aCI6Ii82ODE2NDY5LzMxMjA0MTc5Mi0xNTg2NTc4ZS01OGVjLTQyY2EtODVmYy05YWYxYmNhYjRhN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMjI0NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc1NjUwYmIyOGUyMmM3N2M5MWM2MTA0ZWEwNzFlMjhkOTU1NDgwZDA3MmE1YzczYWE0M2U0OWYwN2MzYmEzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z37mVs_I_WjJ7cMLJGIzBPqxgbmzgVGGzNaVdcojNDM)
> 
> 3. send message to discord channel 2
> 
> The Level 2 course requires different credentials, and you'll have to sign up again to get them. See on the first page:
> 
> https://docs.n8n.io/courses/level-two/#how-do-i-complete-the-course
> 
> > 4. lack of information of the need to add "My ID: {token}" in error workflow
> 
> You're right! I have pushed a fix to change this step to:
> 
> * Text: The workflow `{workflow name}` failed, with the error message: `{execution error message}`. Last node executed: `{name of the last executed node}`. Check this workflow execution here: `{execution URL}` My Unique ID: `{your ID from the course signup email}`
> 
> > 5. all in all, it lacks the solution for the exercises
> 
> I appreciate all the feedback you can give me! If you get stuck, other people will too.

This discussion also took place at the forum (check it here https://community.n8n.io/t/level-2-part-2-generating-file-for-regional-sales/40328 ).

I just saw the documentation and it seems to be way better now and I am happy that I could contribute positively to such a nice project (items 3/4/5).

Regarding PDF (item 1), indeed, I just checked now and you are right. I was trying to do the reverse action as a challenge (not only http file > pdf > json, but also json > binary > PDF). By doing so I got stuck with the absence of the specific node...

About item 2, it still seems that the "sign up" is somehow mixed in a bulk text. As this is critical to start, I'd suggest to highlight it somehow or mention it in the first email for the level 1. As some people might start level 2 after the level 1 (my case), it is easy to assume that they are the same, once the pages "get started" are very similar)...

Thanks for the assistance and improvement on the guide. I am sure the people that come next will benefit from it a lot, as I did.

By the way, any plans to have additional levels or badges?

KR
