### ISSUE TITLE
The node "Edit Field" is not configured in "very-quick-quickstart-workflow"

### ISSUE THREAD

**Issue by andrewchiull** [n8n-io/n8n-docs#1948]
Hi devs,

I'm new to n8n, and I am trying very-quick-quickstart-workflow. The node "Edit Field" seems not configured when I use the template, as the following screenshots:

![Screen Shot 2024-03-05 at 23 23 12](https://github.com/n8n-io/n8n-docs/assets/63439849/143239d9-24c5-4326-8b9a-56b2a4d96da9)
![Screen Shot 2024-03-05 at 23 19 01](https://github.com/n8n-io/n8n-docs/assets/63439849/e9f02a13-a54a-4141-a5e7-3264d6ccd981)

Since the final outputs from messenger are pretty weird, I assume that I should map some original fields in `{{$json.customer_name}}` and `{{$json.customer_description}}` in the node "Edit Field" first? Yet the tutorial didn't tell me to do that.

> Step three: Run the workflow[#](https://docs.n8n.io/try-it-out/quickstart/?ref=weii.dev#step-three-run-the-workflow)
Select Test Workflow. This runs the workflow, loading the data from the Customer Datastore node, then transforming it with Edit Fields. You need this data available in the workflow so that you can work with it in the next step.

Please kindly tell me if I get something wrong, thanks!

Best,
Andrew

**Comment by andrewchiull** [comment]
Also, in the Step two,
> Select **Use workflow** to open the template in your own editor.

Since there is no such a button in the page, I clicked `Use template` and saw something as the following image:

![Screen Shot 2024-03-05 at 23 26 50](https://github.com/n8n-io/n8n-docs/assets/63439849/205e4f9e-cb25-4bff-8b1b-43cc406d937c)

There are no any instructions about these four options in the tutorial doc. I just felt overwhelmed and didn't know what to do about these, so I just clicked the first one.

Please consider revise the docs, thank you!

Best, 
Andrew

**Comment by StarfallProjects** [comment]
Hi! Thanks for reporting this. The example workflow does indeed have errors. I've submitted a fix, but it can take a day or two for template updates to appear. In the mean time, here is the JSON. You can copy this and paste it in to n8n.

```
{
  "name": "Very quick quickstart",
  "nodes": [
    {
      "parameters": {
        "operation": "getAllPeople",
        "returnAll": true
      },
      "id": "cbb6afcc-f900-434d-ad2e-affb31ccf7a9",
      "name": "Customer Datastore",
      "type": "n8n-nodes-base.n8nTrainingCustomerDatastore",
      "position": [
        1000,
        740
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "content": "## About the very quick quickstart workflow\n\nThis is an incomplete workflow, used in the [very quick quickstart](https://docs.n8n.io//try-it-out/quickstart/) tutorial.",
        "height": 220,
        "width": 300
      },
      "id": "1eb939c0-e391-4e3b-9751-889da2de7cf7",
      "name": "Note",
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        460,
        460
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "content": "**Get fake sample data**",
        "height": 300,
        "width": 220
      },
      "id": "c53a8591-9efe-4fb8-993b-6cc309f3240e",
      "name": "Note1",
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        940,
        640
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "content": "**Extract data and prepare it for use in the next node**",
        "height": 300,
        "width": 220
      },
      "id": "c7e35ca4-b180-4280-9e43-a5dda5d3ea97",
      "name": "Note2",
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        1220,
        640
      ],
      "typeVersion": 1
    },
    {
      "parameters": {},
      "id": "94bba884-5cef-4fe6-ba7d-cc7dbe49839c",
      "name": "When clicking \"Test Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "position": [
        760,
        740
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "df041e3c-fc09-4ba2-8e6b-37f2c6a02526",
              "name": "customer_id",
              "value": "={{ $json.id }}",
              "type": "string"
            },
            {
              "id": "bf288953-4fef-4f55-a45f-c223714919c0",
              "name": "customer_name",
              "value": "={{ $json.name }}",
              "type": "string"
            },
            {
              "id": "1cff0b21-6740-4697-9d2c-9bcb045af0be",
              "name": "customer_description",
              "value": "={{ $json.notes }}",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "f6d22d64-c77f-415d-9c34-c7106ba4877a",
      "name": "Edit Fields1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1280,
        740
      ]
    }
  ],
  "pinData": {},
  "connections": {
    "Customer Datastore": {
      "main": [
        [
          {
            "node": "Edit Fields1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking \"Test Workflow\"": {
      "main": [
        [
          {
            "node": "Customer Datastore",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields1": {
      "main": [
        []
      ]
    }
  }
}
```

And thanks for the report of the missing steps. I've updated them, and this should be live now.

Closing this for now, but please file further issues if needed, or ask for help on the [forum](https://community.n8n.io/).
