### ISSUE TITLE
General Documentation Errors and Ambiguity

### ISSUE THREAD

**Issue by lawfulsoftware** [n8n-io/n8n-docs#1995]
I posted the [General Documentation Errors and Ambiguity](https://community.n8n.io/t/several-documentation-errors/43415) in the community but want to ensure that they are seen.

**Comment by StarfallProjects** [comment]
Hi @lawfulsoftware thanks for this. To manage expectations: I am away until April 8th. I'll pick this up and go through it properly when I return.

**Comment by StarfallProjects** [comment]
Note to self: check this in addition to the forum thread https://github.com/n8n-io/n8n/issues/9030

**Comment by StarfallProjects** [comment]
API typo fix: https://github.com/n8n-io/n8n/pull/9142

**Comment by StarfallProjects** [comment]
Reopening: the linked PR clears a lot of the issues raised, but not all.

**Comment by ayatnkw** [comment]
Hi @lawfulsoftware, thanks again for all your feedback. They’ve all been great suggestions, and we’ve made changes where we could, so I'm closing this issue for now. See related PRs for the changes made, and let me know if you have any questions!
