### ISSUE TITLE
Course 1 typo: 'orderId: Number' -->  'orderID: Number'

### ISSUE THREAD

**Issue by classbasics** [n8n-io/n8n-docs#2005]
Course 1 typo: 'orderId: Number' -->  'orderID: Number'

Data from orderID will not insert into Airtable if the Airtable column is called orderId.

https://docs.n8n.io/courses/level-one/chapter-5/chapter-5.4/#whats-next

**Comment by StarfallProjects** [comment]
@bartv42

**Comment by bartv42** [comment]
@classbasics I made this change and found a couple more instances of this typo in this course. Thanks!
