### ISSUE TITLE
presumptuous: Customer Datastore node not mentioned in Exercise

### ISSUE THREAD

**Issue by classbasics** [n8n-io/n8n-docs#2009]
presumptuous: Customer Datastore node not mentioned in Exercise

'Build a workflow that adds five days to an input date.' -> 'Build a workflow that adds five days to an input date from Customer Datastore node.'

https://docs.n8n.io/courses/level-two/chapter-2/#date-time-and-interval-data

**Comment by StarfallProjects** [comment]
@bartv42

**Comment by bartv42** [comment]
@classbasics that's a good suggestion, we're adding this. Thanks!
