### ISSUE TITLE
typo: 'Now that know what Nathan' -> 'Now that we know what Nathan'

### ISSUE THREAD

**Issue by classbasics** [n8n-io/n8n-docs#2010]
typo: 'Now that know what Nathan' -> 'Now that we know what Nathan'

https://docs.n8n.io/courses/level-two/chapter-5/chapter-5.0/#workflow-prerequisites

**Comment by StarfallProjects** [comment]
Thanks for the report! 🙏

Resolved: https://github.com/n8n-io/n8n-docs/pull/2016
