### ISSUE TITLE
Please provide json workflow of answers

### ISSUE THREAD

**Issue by classbasics** [n8n-io/n8n-docs#2012]
Please provide json workflow of answers, including some notes with the nodes.

https://docs.n8n.io/courses/level-two/chapter-5/chapter-5.1/

**Comment by StarfallProjects** [comment]
@bartv42

**Comment by Joffcom** [comment]
Hey @classbasics,

If we provide a workflow with the answers it would take away the fun of learning, Building that workflow is also directly linked to event tracking that tells us if you have built it correctly to pass the course.

For these reasons we will not currently be providing the workflow.
