### ISSUE TITLE
Add FAQ about JQL to Jira Node

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#216]
Users ask how to "get all" tickets from JIRA node but with filters applied. Answer is using JQL queries (an "option" in JIRA Node). FAQ answer should include link to JQL reference. 

Original post in community: 
https://community.n8n.io/t/jira-project-selection/2578

**Comment by tanay1337** [comment]
@harshil1712 Can you pick this up whenever you get the chance? :)

**Comment by tanay1337** [comment]
Fixed here: https://github.com/n8n-io/n8n-docs/pull/279.
