### ISSUE TITLE
Add this workflow to FAQ/ reference for function node

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#220]
A user asked me how they might get the execution time of a portion of a workflow (they are testing API latency, and need to record the ms it took for API to reply). I created this workflow to be generic enough to answer the general question "how do I measure how long a workflow/ portion of workflow took to execute?"

Workflow on n8n.io: https://n8n.io/workflows/717

Not sure exactly where, but I recommend this is linked in the docs. Maybe in the function node, or perhaps in Javascript Snippets cheatsheet. Not too precious where!

**Comment by harshil1712** [comment]
Thanks, @maxtkacz for bringing this up. It is a useful workflow.

@tanay1337, I am also not sure where we should include this. In the Code Snippet documentation, we are sharing code snippets while this is a workflow. Adding it to the FAQ section of the Function node doesn't seem to be the ideal place. It is more of a generic query and not a direct question about the node.

**Comment by tanay1337** [comment]
Makes sense @harshil1712. Since it is well documented, I think the workflow page is the ideal page for this. Could perhaps be a featured workflow after the Workflow page update.
