### ISSUE TITLE
Salesforce docs inaccurate for n8n.cloud

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#222]
On our docs for Salesforce credentials ( ) we state that for n8n.cloud users "You'll only need to enter the Credentials Name and click on the circle button in the OAuth section to connect your Salesforce account to n8n."

This confusing because Add Credentials modal for Salesforce (on n8n.cloud) has an additional "Access Token URL:" field. If the user reads "⛅️ Note for n8n.cloud users", they could understand it to mean "don't touch Access Token URL", even though they would need to.

**Comment by tanay1337** [comment]
Fixed [here](https://github.com/n8n-io/n8n-docs/commit/91aa198613948260053785777f575ac45db4f26e). Thanks @maxtkacz!
