### ISSUE TITLE
Bad link in "Microsoft Teams" page

### ISSUE THREAD

**Issue by doggy8088** [n8n-io/n8n-docs#2437]
Problem Page Link: https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftteams/?#templates-and-examples

![image](https://github.com/user-attachments/assets/9222e52a-32af-40b7-a03a-c5301da1a66a)

Bad link: <https://n8n.io/workflows/680-create,-update-and-send-a-message-to-a-channel-in-microsoft-teams/>

Correct link: <https://n8n.io/workflows/680-create-update-and-send-a-message-to-a-channel-in-microsoft-teams/>

**Comment by Joffcom** [comment]
Sorry for the delay, Thanks for reporting this we should have a fix in place soon to fix all of the bad dynamic links.

**Comment by Joffcom** [comment]
This should now be resolved, Moving to closed. Thanks again for reporting it.
