### ISSUE TITLE
Gmail example to IMAP Email node docs

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#277]
Cloud user asked about Gmail trigger node. Not on immediate roadmap since we have IMAP Email node. Current docs are rather light on how to use IMAP node. Would be great to have another example specifically with gmail where we can point users when they ask for "gmail trigger". Useful then for other email users since we atleast show how to configure it with a mainstream email client. 

https://docs.n8n.io/nodes/n8n-nodes-base.emailReadImap/#basic-operations

**Comment by krynble** [comment]
Working on it =)
