### ISSUE TITLE
Add valid Cron expression generator to Cron node

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#283]
Had to make a custom Cron expression (Mon-Thursday at 9 am). Immediately I googled "Cron expression generator" as I reach for a visual tool for things like this and regex. Was having errors on first two generator tools I found because they were conformed to the popular Quartz spec (which we don't support). I recommend we find a free tool that supports the spec we conform to and link to it in Cron node docs.

**Comment by tanay1337** [comment]
From Jan: https://crontab.guru/

@harshil1712 Can you please pick it up whenever you get the chance? :)
