### ISSUE TITLE
Slack node 2nd example (DM user)

### ISSUE THREAD

**Issue by maxtkacz** [n8n-io/n8n-docs#313]
Was having trouble on how to DM a user directly (instead of posting a message to a chat). Slack is an accessible/ broadly used node (and also will be used heavily in cloud onboarding), so I think it's justifiable to give it a second example like this (i.e. is one of our "top nodes")

**Comment by Vadorequest** [comment]
@maxtkacz https://docs.mattermost.com/developer/webhooks-incoming.html

Use <!channel> or <!here> for groups of users.

Use <@U6WTJ0A1G> to mention a user directly, where `U6WTJ0A1G` is the user Slack ID (Profile > More > Get ID)
