### ISSUE TITLE
Broken redirects in "Daily Weather Notifications ..." and "Automate Product Feedback ..." example workflows

### ISSUE THREAD

**Issue by huonw** [n8n-io/n8n-docs#359]
The https://docs.n8n.io/getting-started/create-your-first-workflow/daily-weather-notifications/#building-the-workflow and https://docs.n8n.io/getting-started/create-your-first-workflow/get-product-feedback/#building-the-workflow sections has the following broken links (they redirect the browser to the locations in parens, which work when visited directly):

- Cron: https://docs.n8n.io/nodes/nodes-library/core-nodes/Cron/ (https://docs.n8n.io/nodes/n8n-nodes-base.cron/)
- OpenWeatherMap: https://docs.n8n.io/nodes/nodes-library/nodes/OpenWeatherMap/ (https://docs.n8n.io/nodes/n8n-nodes-base.openWeatherMap/)
- NoOp: https://docs.n8n.io/nodes/nodes-library/core-nodes/NoOperationDoNothing/ (https://docs.n8n.io/nodes/n8n-nodes-base.noOp/)
- Typeform Trigger: https://docs.n8n.io/nodes/nodes-library/trigger-nodes/TypeformTrigger/ (https://docs.n8n.io/nodes/n8n-nodes-base.typeformTrigger/)
- Set: https://docs.n8n.io/nodes/nodes-library/core-nodes/Set/ (https://docs.n8n.io/nodes/n8n-nodes-base.set/)
- Airtable: https://docs.n8n.io/nodes/nodes-library/nodes/Airtable/ (https://docs.n8n.io/nodes/n8n-nodes-base.airtable/)
- Trello: https://docs.n8n.io/nodes/nodes-library/nodes/Trello/ (https://docs.n8n.io/nodes/n8n-nodes-base.trello/)

The IF and Twilio links work.

Example contents of page for Cron above: 
![image](https://user-images.githubusercontent.com/1203825/103583825-8ac51e80-4f34-11eb-99c5-db658bb61bde.png)

I see this problem in Firefox, Chrome and Safari on macOS. I do not see this problem in Safari on iOS or Chromium on Linux.

**Comment by harshil1712** [comment]
Hey @huonw,

Closing this issue since it got fixed. Thank you for bringing this up 🙂
