### ISSUE TITLE
Twilio Node should be using API keys instead of Account SID and password

### ISSUE THREAD

**Issue by bamboowonder** [n8n-io/n8n-docs#515]
Hi there, the plugin currently uses the Twilio primary account sid and password.  This is pretty risky for production systems, and a pain to manage if they need to be revoked without breaking other systems.

Twilio provides "standard" apikeys and passwords with limited permissions that should be used instead.

https://docs.n8n.io/credentials/twilio/

https://www.twilio.com/docs/iam/keys/api-key

Thank you for your consideration

**Comment by harshil1712** [comment]
Hey @bamboowonder!

Thank you for opening the issue. Can you please open an issue on the [project repo](https://github.com/n8n-io/n8n/issues/new/choose)? Once it gets implemented we will update the documentation as well 🙂

**Comment by bamboowonder** [comment]
ok.  I've opened it here:  https://github.com/n8n-io/n8n/issues/1782

**Comment by harshil1712** [comment]
Thank you @bamboowonder! I will close this issue. Once the changes are implemented, I'll update the documentation. Once again, thank you for bringing this to our notice.
