### ISSUE TITLE
Why does n8n requires docker.sock access in docker-compose example ?

### ISSUE THREAD

**Issue by romualdr** [n8n-io/n8n-docs#518]
Hello ! 👋

In the documentation Server Setup, there is the volume configuration `/var/run/docker.sock:/var/run/docker.sock` in the n8n service declaration; implying that n8n requires an access to the Docker socket to work.

https://docs.n8n.io/reference/server-setup.html#_5-create-docker-compose-file
![image](https://user-images.githubusercontent.com/5497356/118190954-2404c400-b444-11eb-9ec3-9dd7c5bf6233.png)

However, I looked through the documentation to check any reason to do so, but I unfortunately found none.

Does n8n really uses the docker.sock for anything ?
If so, documentation should be clearer about the usage for security and transparency purposes
If not, I guess this is just a typo that should be removed maybe ?

Regards,

**Comment by janober** [comment]
Thanks a lot for making us aware of that @romualdr!

That looks like an error. n8n does generally not need access to it. After I read your question I thought that it is maybe related to traefik (but even there it would have been strange that other containers need access) but also could not find anything in their documentation regarding it. Anyway to be 100% sure did I just follow the Server Setup Guide on a totally new server and did set it up without that line. Works unsurprisingly totally fine without it. We will remove it with the next docs release.

**Comment by romualdr** [comment]
Yes, I think it came from on example on the community forum, where someone
showed this exact configuration, with this exact copy/paste error (
probably from Traefik the config right above the n8n service declaration)

I started n8n.io yesterday without it and it works perfectly as well.

Thank you for your answer.
Rom.
