### ISSUE TITLE
Broken link for 'installation->advanced->security.html' page

### ISSUE THREAD

**Issue by jawaharas** [n8n-io/n8n-docs#589]
The below link in the [Server Setup](https://docs.n8n.io/getting-started/installation/advanced/server-setup.html#example-setup-with-docker-compose) is broken.

https://docs.n8n.io/getting-started/installation/advanced/security.html

**Comment by gpene** [comment]
Fixed in https://github.com/n8n-io/n8n-docs/commit/217836e51cb750774e7a17f704bea44a0694a0e6 - thank you @jawaharas
