### ISSUE TITLE
Misleading statement that /root/.n8n is necessary

### ISSUE THREAD

**Issue by ad-si** [n8n-io/n8n-docs#608]
At https://docs.n8n.io/getting-started/installation/docker-quickstart.html#using-alternate-databases it says that the /root/.n8n directory needs to be persisted since it contains the encryption key for credentials. However, the encryption key can also be provided via the `N8N_ENCRYPTION_KEY` environment variable.

So as far as I can tell /root/.n8n does not need to be persisted, right?
That's very important information if you want to run n8n on an ephemeral hosting service like Google Cloud Run.

**Comment by gpene** [comment]
Thanks @ad-si , added a clarifying note to specify that though it is best practice it is not **required**.
