### ISSUE TITLE
Section about state in containers

### ISSUE THREAD

**Issue by ad-si** [n8n-io/n8n-docs#609]
I assumed that n8n was stateless (except for the database) and could therefore be run on Google Cloud Run. However, I just had the case that I was testing a webhook, and while the container was in the "waiting to receive request" mode, all requests were suddenly routed to another container. This is not a deal breaker, but now I'm wondering what other functionality is not stateless and could cause problems in the future?

**Comment by ad-si** [comment]
So, I have been trying to get it to run reliably on Cloud Run, but without success so far. There seems to be a problem with the activation of n8n when Cloud Run instantiates additional containers. I was getting this error quite often:

`Error: {"code":404,"message":"The requested webhook \"POST a32152f9-267d-49a4-9b2e-6efe8ac43c02\" is not registered`

I have now configured Cloud Run to always run exactly one container (which defeats the whole purpose of Cloud Run) and it has been reliably working since then.

Conceptually, scaling to several containers shouldn't be a problem, so what exactly is going on here?

**Comment by gpene** [comment]
@krynble / @janober Can you help with @ad-si issue here?

**Comment by krynble** [comment]
Hi @ad-si 

Thanks @gpene for mentioning.

Well, in fact, n8n is not stateless. You must run one and only one "main" n8n process.

You can scale webhooks and workers, as stated in our documentation [here](https://docs.n8n.io/getting-started/installation/advanced/scaling-n8n.html#how-it-works).

You can then scale `worker` and `webhook` process as much as you need, but you also need to have a shared Redis instance.

One important thing to note is that once you start n8n once, it will create an encryption key, used to encrypt your data in your database.

This key should be created by your "main n8n instance" and then shared with all workers and webhooks so they can have access to your credentials (like OAuth tokens, api keys, etc.).

I hope this clarifies how to scale n8n.

**Comment by ad-si** [comment]
> You must run one and only one "main" n8n process.

Every container on Google Cloud Run is one new instance of n8n with its own main process.


> One important thing to note is that once you start n8n once, it will create an encryption key, used to encrypt your data in your database.

I set the the encryption key via the `N8N_ENCRYPTION_KEY` flag so it's also the same for all Cloud Run instances

So this doesn't explain the problems.


Is there maybe some kind of problem when several n8n instances share the same Postgres database? If so, I think this shouldn't be a problem. All they should do with the database is load the workflows and write the logs of the events. This itself shouldn't cause any interference between the n8n instances. What am I missing?

**Comment by harshil1712** [comment]
Hey @ad-si,

Since this is converting into a discussion, let's move this to the [community forum](https://community.n8n.io). This way others in the community can also benefit from it :)

**Comment by krynble** [comment]
Just to finish what I was already writing:

If you are running only one container, with a single n8n instance (no scaling at all), then you should be fine. If you run multiple containers, you might have issues with a few of the trigger types.

Let's say you have a workflow that is triggered by a cron or a time interval. With multiple n8n instances, you will have multiple triggers, therefore causing duplication of work.

Now if your workflows are based **only** on webhooks (i.e. external http requests) then you should have no problem with multiple n8n instances sharing the same database. This is the only situation when you can say that n8n is "stateless".
