### ISSUE TITLE
no idList

### ISSUE THREAD

**Issue by jorjik** [n8n-io/n8n-docs#681]
Do step 4 https://docs.n8n.io/nodes/n8n-nodes-base.trello/#how-do-i-find-the-list-id
see https://i.imgur.com/S4FWTyB.png

**Comment by miru955** [comment]
Hi @jorjik, your url is pointing to a board. If you point it to a card, then you will see the key "idList" close to the beginning.

**Comment by harshil1712** [comment]
Hey @jorjik,
As mentioned by @miru955 you have to add `.json` at the end of your card's URL. If you still need help feel free to create a new topic on the [community forum](https://community.n8n.io).
