### ISSUE TITLE
Feedback buttons doesn't show any response

### ISSUE THREAD

**Issue by arps18** [n8n-io/n8n-docs#710]
- The Feedback Button (both i.e 👍 &👎) don't seem to get selected in [Automating a (Real-world) Use Case](https://docs.n8n.io/courses/level-one/chapter-3.html#understanding-the-scenario) page. 
- Page Link: [https://docs.n8n.io/courses/level-one/chapter-3.html#understanding-the-scenario](https://docs.n8n.io/courses/level-one/chapter-3.html#understanding-the-scenario)

Steps to Reproduce the bug: 
1. Scroll to the Feedback section at the bottom of the page.
2. Select either of the 2 buttons.

Browser: Brave Browser

**Comment by harshil1712** [comment]
Hey @arps18,

Thank you for opening the issue and bringing this to our notice. The bug is now fixed and you should be able to share your feedback :)
