### ISSUE TITLE
Update license title in Docs

### ISSUE THREAD

**Issue by Bumpyride** [n8n-io/n8n-docs#766]
The license title on [Docs](https://docs.n8n.io/reference/license.html) page still showing `Apache 2.0 with Commons Clause` instead of `Sustainable Use License`. However, the link points correctly to the new [LICENSE.md](https://github.com/n8n-io/n8n/blob/master/packages/cli/LICENSE.md) file.

**Comment by StarfallProjects** [comment]
Thank you! Fixed by: https://github.com/n8n-io/n8n-docs/pull/768
