### ISSUE TITLE
Change license name in README.md (this repo)

### ISSUE THREAD

**Issue by Bumpyride** [n8n-io/n8n-docs#769]
License section in README.md (https://github.com/n8n-io/n8n-docs#license)
n8n-docs is fair-code licensed under **Apache 2.0 with Commons Clause** should pobably read  
n8n-docs is fair-code licensed under **Sustainable Use License**.

BTW and FWIW, I think your decision to move away from the Commons Clause was wise. I believe that the wording of the Common Clause makes it a time-bomb, and not "Fair-code" at all.

**Comment by StarfallProjects** [comment]
And thank you again! Fixed by: https://github.com/n8n-io/n8n-docs/pull/770
