### ISSUE TITLE
Create First Node Documentation - spelling/mistake

### ISSUE THREAD

**Issue by brianinoa** [n8n-io/n8n-docs#860]
[Create First Node Documentation](https://docs.n8n.io/integrations/creating-nodes/code/create-first-node/#adding-required-fields)

Let’s make the Node Editor View ask for these parameters:

'dd the following under description.properties in packages/nodes-base/nodes/FriendGrid/FriendGrid.node.ts.

Should be: Add the following under description.properties...

**Comment by StarfallProjects** [comment]
Fixed
